### PR TITLE
updating website entry for German Chapter

### PR DESCRIPTION
**Pull request by vrms**
added udated link to meetup site for https://erpnext.org/chapter-list

### CODE REVIEW

**Comment by vrms** [comment]
@asbasawaraj sorry, I keep coming back to you ... any chance to get this merged some time? You can also point me to whomever might be a better contct person for such requests. @revant maybe?

**Comment by vrms** [comment]
thanks @asbasawaraj . The new link is still not inline though. Does the ERPNext instance behind erpnext.org need a `bench update` in order to see the change?

**Comment by vrms** [comment]
sorry to bother you again @asbasawaraj . Let me know wheter anzbody else is in charge of this matter.

The link to the German Chapter on erpnext.org/chapter-list still is the old (dead) link even though you merged the PR with the new updated link. Can you either make this happen or advise how I can take action.

**Comment by master-hora** [comment]
Hi @asbasawaraj. As I see the update is live now. Thank you! By the way. What's the difference between https://erpnext.org/chapters (24 entries, without Germany) and https://erpnext.org/chapter-list (9 entries with Germany)? Please tell me where to ask that question if this is not the right place? Kind regards. Klaus

**Comment by vrms** [comment]
> What's the difference between https://erpnext.org/chapters (24 entries, without Germany) and https://erpnext.org/chapter-list (9 entries with Germany)?

I believe chapter-list is hardcoded in the websites html code. while /chapters  shows ERPNext doctypes. At some point in history it was decided (no idea about the reason) not to use the doctype chapters but to hardcode links to meetup pages

**Comment by master-hora** [comment]
@vrms OK, thanks!

**Pull request merged**
